#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn reinstall

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  cd ./android/
  ./gradlew clean
  cd ..
fi

# if [[ "$OSTYPE" == "darwin" ]]; then
#   cd ./ios/
#   pod install
#   cd ..
# fi

exec bash